name: Automatic Branch Synchronization

on:
  pull_request:
    branches: [ development, qa, staging, master ]
    types: [opened, synchronize, reopened]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      
      - name: Check and sync branches
        run: |
          # Get the base branch of the PR
          BASE_BRANCH="${{ github.base_ref }}"
          
          # Define upstream branch based on PR's base branch
          case "$BASE_BRANCH" in
            "development")
              upstream_branch="qa"
              ;;
            "qa")
              upstream_branch="staging"
              ;;
            "staging")
              upstream_branch="master"
              ;;
            "master")
              upstream_branch=""
              ;;
          esac
          
          if [ ! -z "$upstream_branch" ]; then
            echo "Checking if $BASE_BRANCH needs sync with $upstream_branch"
            
            # Fetch all branches
            git fetch origin $BASE_BRANCH
            git fetch origin $upstream_branch
            
            # Check if base branch contains all commits from upstream
            if ! git merge-base --is-ancestor origin/$upstream_branch origin/$BASE_BRANCH; then
              echo "WARNING: $BASE_BRANCH is not up-to-date with $upstream_branch"
              echo "This PR cannot be merged until $BASE_BRANCH is synchronized with $upstream_branch"
              exit 1
            fi
          fi