name: Branch Validation Check

on:
  pull_request:
    branches: [ development, qa, staging, master ]

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Validate branch synchronization
        run: |
          # Get the base branch of the PR
          BASE_BRANCH="${{ github.base_ref }}"
          
          # Define upstream branch based on PR's base branch
          case "$BASE_BRANCH" in
            "development")
              upstream_branch="qa"
              ;;
            "qa")
              upstream_branch="staging"
              ;;
            "staging")
              upstream_branch="master"
              ;;
            "master")
              upstream_branch=""
              ;;
          esac
          
          if [ ! -z "$upstream_branch" ]; then
            echo "Checking if $BASE_BRANCH is up-to-date with $upstream_branch"
            
            # Fetch all branches
            git fetch origin $BASE_BRANCH
            git fetch origin $upstream_branch
            
            # Check if base branch contains all commits from upstream
            if ! git merge-base --is-ancestor origin/$upstream_branch origin/$BASE_BRANCH; then
              echo "ERROR: $BASE_BRANCH is missing commits from $upstream_branch"
              echo "Please merge $upstream_branch into $BASE_BRANCH first"
              exit 1
            fi
          fi 