name: Branch Validation Check

on:
  pull_request:
    branches: [ development, qa, staging, master ]

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Validate branch synchronization
        run: |
          # Define branch hierarchy
          case "${{ github.ref }}" in
            refs/heads/development)
              upstream_branch="qa"
              ;;
            refs/heads/qa)
              upstream_branch="staging"
              ;;
            refs/heads/staging)
              upstream_branch="master"
              ;;
            refs/heads/master)
              upstream_branch=""
              ;;
          esac
          
          if [ ! -z "$upstream_branch" ]; then
            git fetch origin $upstream_branch
            if ! git merge-base --is-ancestor origin/$upstream_branch HEAD; then
              echo "ERROR: Current branch is missing commits from $upstream_branch"
              exit 1
            fi
          fi 